CMTPATH=/data/BOSSParallel/CEPCDataModel:/data/BOSSParallel/sniper:/data/BOSSParallel/ExternalInterface
CMT_tag=$(tag)
CMTROOT=/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/CMT/v1r25
CMT_root=/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/CMT/v1r25
CMTVERSION=v1r25
CMT_offset=/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/data/BOSSParallel/CEPCDataModel/InstallArea/${CMTCONFIG}/bin:/data/BOSSParallel/sniper/InstallArea/${CMTCONFIG}/bin:/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/CMT/v1r25/${CMTBIN}:/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/Gaudi/bin:/cvmfs/sft.cern.ch/lcg/releases/DD4hep/01-12-01-65a08/x86_64-slc6-gcc8-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/Geant4/10.06.p01-1349a/x86_64-slc6-gcc8-opt/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/GEAR/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/plcio/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/podio/bin:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/LCIO/bin:/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/scripts:/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/bin:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.30-e5b21/x86_64-slc6/bin:/cvmfs/sft.cern.ch/lcg/contrib/git/bin:/usr/local/gcc/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/bin:/usr/externals/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/java/latest/bin:/root/bin:/data/BOSSParallel/CLHEP/bin:/data/BOSSParallel/jsoncpp/include/
CLASSPATH=/cvmfs/bes3.ihep.ac.cn/bes3sw/ExternalLib/SLC6/contrib/CMT/v1r25/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-std=c++11 -fPIC -pipe -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp --log=./install.history 
uninstall_command=python $(SniperPolicy_root)/cmt/fragments/install.py -u --log=./install.history 
cmt_installarea_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl65-gcc830
UseCase_tag=$(tag)
USECASEROOT=/data/BOSSParallel/CEPCDataModel/Examples/UseCase
UseCase_root=/data/BOSSParallel/CEPCDataModel/Examples/UseCase
USECASEVERSION=v0
UseCase_cmtpath=/data/BOSSParallel/CEPCDataModel
UseCase_offset=Examples
UseCase_project=CEPCDataModel
SniperKernel_tag=$(tag)
SNIPERKERNELROOT=/data/BOSSParallel/sniper/SniperKernel
SniperKernel_root=/data/BOSSParallel/sniper/SniperKernel
SNIPERKERNELVERSION=v2
SniperKernel_cmtpath=/data/BOSSParallel/sniper
SniperKernel_project=sniper
SniperPolicy_tag=$(tag)
SNIPERPOLICYROOT=/data/BOSSParallel/sniper/SniperPolicy
SniperPolicy_root=/data/BOSSParallel/sniper/SniperPolicy
SNIPERPOLICYVERSION=v0
SniperPolicy_cmtpath=/data/BOSSParallel/sniper
SniperPolicy_project=sniper
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined 
application_linkopts=-Wl,--export-dynamic 
BINDIR=$(tag)
remove_command=$(cmt_uninstallarea_command)
Boost_tag=$(tag)
BOOSTROOT=/data/BOSSParallel/ExternalInterface/Externals/Boost
Boost_root=/data/BOSSParallel/ExternalInterface/Externals/Boost
BOOSTVERSION=v0
Boost_cmtpath=/data/BOSSParallel/ExternalInterface
Boost_offset=Externals
Boost_project=ExternalInterface
Python_tag=$(tag)
PYTHONROOT=/data/BOSSParallel/ExternalInterface/Externals/Python
Python_root=/data/BOSSParallel/ExternalInterface/Externals/Python
PYTHONVERSION=v0
Python_cmtpath=/data/BOSSParallel/ExternalInterface
Python_offset=Externals
Python_project=ExternalInterface
Python_linkopts= `pkg-config --libs python` 
Python_cppflags= `pkg-config --cflags python` 
Boost_linkopts= -lboost_python 
includes= $(ppcmd)"$(UseCase_root)"  $(ppcmd)"$(srcdir)" $(ppcmd)"/data/BOSSParallel/CEPCDataModel/InstallArea/include" $(ppcmd)"/data/BOSSParallel/sniper/InstallArea/include" $(use_includes)
PYTHONPATH=/data/BOSSParallel/CEPCDataModel/InstallArea/python:/data/BOSSParallel/sniper/InstallArea/python:/data/BOSSParallel/CEPCDataModel/InstallArea/amd64_linux26/lib:/data/BOSSParallel/sniper/InstallArea/amd64_linux26/lib:/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/DD4hep/01-12-01-65a08/x86_64-slc6-gcc8-opt/lib/python2.7/site-packages:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/podio/python:/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/python:/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/lib:/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/lib/python2.7/site-packages:/usr/lib64/python
SniperKernel_shlibflags= -lpthread -std=c++11 -lboost_python -lboost_system
SniperKernel_linkopts= -lSniperKernel  -lSniperPython 
SniperKernel_stamps=${SNIPERKERNELROOT}/${BINDIR}/SniperPython.stamp 
SniperKernel_linker_library=SniperPython
SniperPython_dependencies=SniperKernel
SniperPython_shlibflags= -lSniperKernel 
AlgLevelParallel_tag=$(tag)
ALGLEVELPARALLELROOT=/data/BOSSParallel/sniper/ParaPack/AlgLevelParallel
AlgLevelParallel_root=/data/BOSSParallel/sniper/ParaPack/AlgLevelParallel
ALGLEVELPARALLELVERSION=v0
AlgLevelParallel_cmtpath=/data/BOSSParallel/sniper
AlgLevelParallel_offset=ParaPack
AlgLevelParallel_project=sniper
tbb_tag=$(tag)
TBBROOT=/data/BOSSParallel/ExternalInterface/Externals/tbb
tbb_root=/data/BOSSParallel/ExternalInterface/Externals/tbb
TBBVERSION=v0
tbb_cmtpath=/data/BOSSParallel/ExternalInterface
tbb_offset=Externals
tbb_project=ExternalInterface
tbb_linkopts= -L/data/BOSSParallel/tbb20170226/lib/intel64/gcc4.7 -ltbb 
jsoncpp_tag=$(tag)
JSONCPPROOT=/data/BOSSParallel/ExternalInterface/Externals/jsoncpp
jsoncpp_root=/data/BOSSParallel/ExternalInterface/Externals/jsoncpp
JSONCPPVERSION=v0
jsoncpp_cmtpath=/data/BOSSParallel/ExternalInterface
jsoncpp_offset=Externals
jsoncpp_project=ExternalInterface
jsoncpp_linkopts= -L/usr/local/jsoncpp -ljsoncpp --std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0
AlgLevelParallel_use_linkopts= -lrt -L./lib -lboost_system -pthread -fPIC
AlgLevelParallel_linkopts= -lAlgLevelParallel 
AlgLevelParallel_stamps=${ALGLEVELPARALLELROOT}/${BINDIR}/AlgLevelParallel.stamp 
AlgLevelParallel_linker_library=AlgLevelParallel
ROOT_tag=$(tag)
ROOTROOT=/data/BOSSParallel/ExternalInterface/Externals/ROOT
ROOT_root=/data/BOSSParallel/ExternalInterface/Externals/ROOT
ROOTVERSION=v0
ROOT_cmtpath=/data/BOSSParallel/ExternalInterface
ROOT_offset=Externals
ROOT_project=ExternalInterface
ROOT_home=${ROOTSYS}
ROOT_cppflags=`root-config --cflags` -Wno-long-long 
ROOT_linkopts=`root-config --libs`
rootcint="$(ROOT_home)/bin/rootcint"
ALPDataIO_tag=$(tag)
ALPDATAIOROOT=/data/BOSSParallel/CEPCDataModel/ALPDataIO
ALPDataIO_root=/data/BOSSParallel/CEPCDataModel/ALPDataIO
ALPDATAIOVERSION=v0
ALPDataIO_cmtpath=/data/BOSSParallel/CEPCDataModel
ALPDataIO_project=CEPCDataModel
PODIO_tag=$(tag)
PODIOROOT=/data/BOSSParallel/ExternalInterface/Externals/PODIO
PODIO_root=/data/BOSSParallel/ExternalInterface/Externals/PODIO
PODIOVERSION=v0
PODIO_cmtpath=/data/BOSSParallel/ExternalInterface
PODIO_offset=Externals
PODIO_project=ExternalInterface
PODIO_linkopts= -L/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/podio/lib64/ -lpodio -lpodioRootIO
ALPDataIO_linkopts= -lALPDataIO 
ALPDataIO_stamps=${ALPDATAIOROOT}/${BINDIR}/ALPDataIO.stamp 
ALPDataIO_linker_library=ALPDataIO
UseCase_linkopts= -lUseCase 
UseCase_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(UseCase_use_linkopts)
UseCase_use_linkopts=    $(AlgLevelParallel_linkopts)  $(ALPDataIO_linkopts)  $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(tbb_linkopts)  $(jsoncpp_linkopts)  $(ROOT_linkopts)  $(PODIO_linkopts) 
UseCase_stamps=${USECASEROOT}/${BINDIR}/UseCase.stamp 
UseCase_linker_library=UseCase
tag=amd64_linux26
package=UseCase
version=v0
PACKAGE_ROOT=$(USECASEROOT)
srcdir=../src
bin=../$(UseCase_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/data/BOSSParallel/CEPCDataModel/Examples/UseCase/amd64_linux26/
project=CEPCDataModel
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(sniper_installarea_prefix)/$(CMTCONFIG)/lib $(sniper_installarea_prefix)/share/lib $(sniper_installarea_prefix)/share/bin $(CEPCDataModel_installarea_prefix)/$(CMTCONFIG)/lib $(CEPCDataModel_installarea_prefix)/share/lib $(CEPCDataModel_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(UseCase_linkopts)  $(AlgLevelParallel_linkopts)  $(ALPDataIO_linkopts)  $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(tbb_linkopts)  $(jsoncpp_linkopts)  $(ROOT_linkopts)  $(PODIO_linkopts) 
ExternalInterface_installarea_prefix=$(cmt_installarea_prefix)
ExternalInterface_installarea_prefix_remove=$(ExternalInterface_installarea_prefix)
LD_LIBRARY_PATH=/data/BOSSParallel/CEPCDataModel/InstallArea/${CMTCONFIG}/lib:/data/BOSSParallel/sniper/InstallArea/${CMTCONFIG}/lib:/data/BOSSParallel/CEPCDataModel/LCIO15/lib:/data/BOSSParallel/CEPCDataModel/GEAR/lib:/data/BOSSParallel/CEPCDataModel/DD4hep/lib:/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/lib:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/K4FWCore/lib:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/Gaudi/lib:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/Pandora/LCContent/lib:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/Pandora/PandoraSDK/lib:/cvmfs/sft.cern.ch/lcg/releases/DD4hep/01-12-01-65a08/x86_64-slc6-gcc8-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/XercesC/3.1.3-b3bf1/x86_64-slc6-gcc8-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/Geant4/10.06.p01-1349a/x86_64-slc6-gcc8-opt/lib64:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/GEAR/lib:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/plcio/lib:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/EDM4hep/lib64:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/podio/lib64:/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/LCIO/lib:/cvmfs/sft.cern.ch/lcg/releases/java/8u222-884d8/x86_64-slc6-gcc8-opt/jre/lib/amd64:/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/lib64:/cvmfs/sft.cern.ch/lcg/views/LCG_97/x86_64-slc6-gcc8-opt/lib:/cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/lib:/cvmfs/sft.cern.ch/lcg/releases/gcc/8.3.0-cebb0/x86_64-slc6/lib64:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.30-e5b21/x86_64-slc6/lib:/cvmfs/sft.cern.ch/lcg/contrib/git/lib64:/usr/local/lib:/usr/local/gcc/lib64:/usr/lib64/classads:/usr/lib64:/usr/lib:/cvmfs/sft.cern.ch/lcg/releases/R/3.2.5-7cecf/x86_64-slc6-gcc8-opt/lib64/R/library/readr/rcon:/cvmfs/sft.cern.ch/lcg/releases/clhep/2.4.1.3-78165/x86_64-slc6-gcc8-opt/lib:/data/BOSSParallel/CLHEP/lib
sniper_installarea_prefix=$(cmt_installarea_prefix)
sniper_installarea_prefix_remove=$(sniper_installarea_prefix)
CEPCDataModel_installarea_prefix=$(cmt_installarea_prefix)
CEPCDataModel_installarea_prefix_remove=$(CEPCDataModel_installarea_prefix)
cmt_installarea_linkopts= -L/data/BOSSParallel/CEPCDataModel/$(CEPCDataModel_installarea_prefix)/$(CMTCONFIG)/lib  -L/data/BOSSParallel/sniper/$(sniper_installarea_prefix)/$(CMTCONFIG)/lib 
ExternalInterface_home=/data/BOSSParallel/ExternalInterface
sniper_home=/data/BOSSParallel/sniper
CEPCDataModel_home=/data/BOSSParallel/CEPCDataModel
CEPCDataModel_install_include= /data/BOSSParallel/CEPCDataModel/$(CEPCDataModel_installarea_prefix)/include 
sniper_install_include= /data/BOSSParallel/sniper/$(sniper_installarea_prefix)/include 
sniper_python_path=/data/BOSSParallel/sniper/$(sniper_installarea_prefix)/$(tag)/lib
CEPCDataModel_python_path=/data/BOSSParallel/CEPCDataModel/$(CEPCDataModel_installarea_prefix)/$(tag)/lib
sniper_install_python=/data/BOSSParallel/sniper/$(sniper_installarea_prefix)/python
CEPCDataModel_install_python=/data/BOSSParallel/CEPCDataModel/$(CEPCDataModel_installarea_prefix)/python
CMTINSTALLAREA=/data/BOSSParallel/CEPCDataModel/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(AlgLevelParallel_root)/cmt/requirements $(ALPDataIO_root)/cmt/requirements $(SniperKernel_root)/cmt/requirements $(SniperPolicy_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(tbb_root)/cmt/requirements $(jsoncpp_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(PODIO_root)/cmt/requirements 
use_includes= $(ppcmd)"$(AlgLevelParallel_root)/src" $(ppcmd)"$(ALPDataIO_root)/src" $(ppcmd)"$(SniperKernel_root)/src" $(ppcmd)"$(SniperPolicy_root)/src" $(ppcmd)"/usr/include" $(ppcmd)"$(Python_root)/src" $(ppcmd)"/data/BOSSParallel/tbb20170226/include" $(ppcmd)"/data/BOSSParallel/jsoncpp/include" $(ppcmd)"/cvmfs/sft.cern.ch/lcg/releases/ROOT/v6.20.02-d9e99/x86_64-slc6-gcc8-opt/include" $(ppcmd)"/cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/97.0.0/podio/include/" 
use_fincludes= $(use_includes)
use_stamps=  $(UseCase_stamps)  $(AlgLevelParallel_stamps)  $(ALPDataIO_stamps)  $(SniperKernel_stamps)  $(SniperPolicy_stamps)  $(Boost_stamps)  $(Python_stamps)  $(tbb_stamps)  $(jsoncpp_stamps)  $(ROOT_stamps)  $(PODIO_stamps) 
use_cflags=  $(UseCase_cflags)  $(AlgLevelParallel_cflags)  $(ALPDataIO_cflags)  $(SniperKernel_cflags)  $(SniperPolicy_cflags)  $(Boost_cflags)  $(Python_cflags)  $(tbb_cflags)  $(jsoncpp_cflags)  $(ROOT_cflags)  $(PODIO_cflags) 
use_pp_cflags=  $(UseCase_pp_cflags)  $(AlgLevelParallel_pp_cflags)  $(ALPDataIO_pp_cflags)  $(SniperKernel_pp_cflags)  $(SniperPolicy_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(tbb_pp_cflags)  $(jsoncpp_pp_cflags)  $(ROOT_pp_cflags)  $(PODIO_pp_cflags) 
use_cppflags=  $(UseCase_cppflags)  $(AlgLevelParallel_cppflags)  $(ALPDataIO_cppflags)  $(SniperKernel_cppflags)  $(SniperPolicy_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(tbb_cppflags)  $(jsoncpp_cppflags)  $(ROOT_cppflags)  $(PODIO_cppflags) 
use_pp_cppflags=  $(UseCase_pp_cppflags)  $(AlgLevelParallel_pp_cppflags)  $(ALPDataIO_pp_cppflags)  $(SniperKernel_pp_cppflags)  $(SniperPolicy_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(tbb_pp_cppflags)  $(jsoncpp_pp_cppflags)  $(ROOT_pp_cppflags)  $(PODIO_pp_cppflags) 
use_fflags=  $(UseCase_fflags)  $(AlgLevelParallel_fflags)  $(ALPDataIO_fflags)  $(SniperKernel_fflags)  $(SniperPolicy_fflags)  $(Boost_fflags)  $(Python_fflags)  $(tbb_fflags)  $(jsoncpp_fflags)  $(ROOT_fflags)  $(PODIO_fflags) 
use_pp_fflags=  $(UseCase_pp_fflags)  $(AlgLevelParallel_pp_fflags)  $(ALPDataIO_pp_fflags)  $(SniperKernel_pp_fflags)  $(SniperPolicy_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(tbb_pp_fflags)  $(jsoncpp_pp_fflags)  $(ROOT_pp_fflags)  $(PODIO_pp_fflags) 
use_libraries= $(AlgLevelParallel_libraries)  $(ALPDataIO_libraries)  $(SniperKernel_libraries)  $(SniperPolicy_libraries)  $(Boost_libraries)  $(Python_libraries)  $(tbb_libraries)  $(jsoncpp_libraries)  $(ROOT_libraries)  $(PODIO_libraries) 
fincludes= $(includes)
UseCase_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
UseCase_python_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_more_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= UseCase UseCase_python install_more_includes 
all_constituents= $(constituents)
constituentsclean= install_more_includesclean UseCase_pythonclean UseCaseclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
